# Generated by Django 5.0.3 on 2024-04-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
