# Generated by Django 5.0.4 on 2024-04-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
