# Generated by Django 5.0.4 on 2024-04-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_remove_category_product_categoryproductconnector"),
        ("categories", "0002_remove_category_user_alter_category_name_and_more"),
    ]

    operations = []
