# Generated by Django 5.0.4 on 2024-04-21 16:56

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(default=None, null=True, upload_to=users.models.upload_to_profile_image),
        ),
    ]
