# Generated by Django 5.0.4 on 2024-04-17 08:26

from django.db import migrations, models

import products.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description_img",
            field=models.ImageField(default=None, null=True, upload_to=products.models.upload_to_description),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_img",
            field=models.ImageField(default=None, null=True, upload_to=products.models.upload_to_thumbnail),
        ),
    ]
