# Generated by Django 5.0.4 on 2024-04-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description_img",
            field=models.ImageField(default=None, null=True, upload_to="product/img/description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_text",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_img",
            field=models.ImageField(default=None, null=True, upload_to="product/img/thumbnail"),
        ),
    ]
