# Generated by Django 5.0.4 on 2024-04-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_description_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description_img",
            field=models.ImageField(default=None, upload_to="product/img/description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_text",
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_img",
            field=models.ImageField(default=None, upload_to="product/img/thumbnail"),
        ),
    ]
