# Generated by Django 5.0.4 on 2024-04-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_description_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description_img",
            field=models.ImageField(default=None, null=True, upload_to="product/img/description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_img",
            field=models.ImageField(default=None, null=True, upload_to="product/img/thumbnail"),
        ),
    ]
