# Generated by Django 5.0.4 on 2024-04-17 08:26

from django.db import migrations, models

import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="image_url",
            field=models.ImageField(default=None, null=True, upload_to=reviews.models.upload_to_review_image),
        ),
    ]
