# Generated by Django 5.0.4 on 2024-04-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="departure_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="return_date",
            field=models.DateField(),
        ),
    ]
