# Generated by Django 5.0.4 on 2024-04-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_departure_date_alter_order_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="people",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="pet",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="sale_price",
            field=models.IntegerField(),
        ),
    ]
