# Generated by Django 5.0.4 on 2024-04-11 06:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0002_alter_usercoupon_status"),
        ("orders", "0002_order_option_peoples_order_option_pets_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="option_peoples",
            new_name="people",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="option_pets",
            new_name="pet",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="coupons.coupon"),
        ),
        migrations.AddField(
            model_name="order",
            name="departure_date",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="return_date",
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "신용카드"),
                            ("bank_transfer", "무통장 입금"),
                            ("toss_pay", "토스페이"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending"),
                            ("SUCCESS", "success"),
                            ("FAILED", "failed"),
                            ("CANCELLED", "cancelled"),
                            ("REFUNDED", "refunded"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orders.order")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
