# Generated by Django 5.0.4 on 2024-04-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_people_alter_order_pet_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="pet",
        ),
    ]
