# Generated by Django 5.0.4 on 2024-04-11 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0002_alter_usercoupon_status"),
        ("orders", "0003_rename_option_peoples_order_people_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="coupon",
        ),
        migrations.AddField(
            model_name="order",
            name="UserCoupon",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="coupons.usercoupon"),
        ),
        migrations.AlterField(
            model_name="order",
            name="sale_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("CANCEL", "cancel"), ("PAID", "paid"), ("ORDERED", "ordered")],
                default="ordered",
                max_length=7,
            ),
        ),
    ]
